import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Script from "next/script"; // 1. 导入 Script 组件

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}

        {/* Easy-Peasy.AI Chatbot */}
        <Script
          src="https://bots.easy-peasy.ai/chat.min.js"
          data-chat-url="https://bots.easy-peasy.ai/bot/75718f5c-f941-4636-b7ea-df0473c95a3c"
          data-btn-position="bottom-right"
          data-widget-btn-color="#6366f1"
          strategy="lazyOnload"
        />
      </body>
    </html>
  );
}