import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Script from "next/script"; // 1. 导入 Script 组件

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}

        {/* Botpress Chatbot */}
        <Script
          src="https://cdn.botpress.cloud/webchat/v3.1/inject.js"
          strategy="lazyOnload"
        />
        <Script id="botpress-config" strategy="lazyOnload">
          {`
            function initBotpress() {
              if (window.botpress) {
                window.botpress.on("webchat:ready", () => {
                  window.botpress.open();
                });
                window.botpress.init({
                  "botId": "91edec7c-4588-43a3-9901-ab4a9e12fd9d",
                  "configuration": {
                    "version": "v1",
                    "botName": "AI Support Agent",
                    "botAvatar": "https://files.bpcontent.cloud/2025/08/01/07/20250801072352-TJM4E5EE.png",
                    "botDescription": "I can help you resolve issues and guide you in using AI-powered content creation and design tools. Ask me anything about features, troubleshooting, or getting the most out of your AI tools experience.",
                    "website": {
                      "title": "Website",
                      "link": "https://ai-shared.netlify.app/"
                    },
                    "email": {},
                    "phone": {},
                    "termsOfService": {},
                    "privacyPolicy": {},
                    "color": "#183C6C",
                    "variant": "solid",
                    "headerVariant": "glass",
                    "themeMode": "light",
                    "fontFamily": "inter",
                    "radius": 2,
                    "feedbackEnabled": true,
                    "footer": "[⚡ by Botpress](https://botpress.com/?from=webchat)"
                  },
                  "clientId": "4e6f3ff0-3417-4488-a841-e46837b50bd4"
                });
              } else {
                setTimeout(initBotpress, 100);
              }
            }
            initBotpress();
          `}
        </Script>
      </body>
    </html>
  );
}