"use client";

import React, { useState, useMemo } from 'react';

//-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
// TYPE DEFINITIONS (TypeScript Interfaces)
//-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=

interface LanguageText {
  zh: string;
  en: string;
}

interface ListItem {
  type: 'list';
  items: LanguageText[];
}

interface Paragraph {
  type: 'paragraph';
  content: LanguageText;
}

interface TableData {
  type: 'table';
  headers: LanguageText[];
  rows: (LanguageText[])[];
  caption: LanguageText;
}

interface Warning {
  type: 'warning';
  content: LanguageText;
}

interface Image {
  type: 'image';
  src: string;
  alt: LanguageText;
  caption?: LanguageText;
}

type SectionContent = ListItem | Paragraph | TableData | Warning | Image;

interface Section {
  id: string;
  title: LanguageText;
  content: SectionContent[];
}

interface Part {
  id: string;
  title: LanguageText;
  introduction?: LanguageText;
  sections: Section[];
}

//-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
// DATA SOURCE (Bilingual Content)
//-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=

const guideData: Part[] = [
  {
    id: 'intro-part',
    title: {
      zh: '自动化评估权威指南：从文档到数据的 Microsoft Forms 与 Teams 之旅',
      en: 'The Definitive Guide to Automated Assessment: From Document to Data with Microsoft Forms and Teams',
    },
    introduction: {
      zh: '数字学习环境的演进为教育工作者提供了强大的工具，以简化管理任务并提高教学效率。本指南详细介绍了 Microsoft 365 生态系统中的一个完整工作流程，该流程使用 Microsoft Forms 将静态文档转换为动态、自动评分的测验，然后利用 Microsoft Teams 作为作业分发、管理和成绩跟踪的中心枢纽。这个过程不仅仅是技术上的便利；它是一种战略性方法，通过自动化评估周期来倍增教育工作者的能力，从而解放宝贵的时间用于数据分析、个性化反馈和直接的学生指导。本报告将引导您完成从将旧的 Word 或 PDF 文件转换为智能数字测验，到分析学生生成的丰富表现数据的整个过程。',
      en: 'The evolution of digital learning environments has presented educators with powerful tools to streamline administrative tasks and enhance pedagogical effectiveness. This guide details a comprehensive workflow within the Microsoft 365 ecosystem that transforms static documents into dynamic, auto-graded quizzes using Microsoft Forms, and then leverages Microsoft Teams as a centralized hub for assignment distribution, management, and grade tracking. This process represents more than a technological convenience; it is a strategic approach that multiplies an educator\'s capacity by automating the assessment cycle, thereby liberating valuable time for data analysis, personalized feedback, and direct student instruction. This report will navigate the complete journey, from converting a legacy Word or PDF file into an intelligent digital quiz to analyzing the rich performance data generated by students.',
    },
    sections: [],
  },
  {
    id: 'part1',
    title: {
      zh: '第一部分：将现有材料转换为数字测验',
      en: 'Part I: Transforming Existing Materials into Digital Quizzes',
    },
    introduction: {
      zh: '此工作流程的基础阶段涉及将现有教育内容高效地转换为交互式数字格式。整个自动化评估过程的成功取决于这初步的质量和准确性，它弥合了传统材料与现代数字平台之间的差距。这种方法承认教育工作者已经拥有的大量内容库，并提供了一条直接的数字化途径，而无需为从头开始重新创建每个评估而付出高昂的时间成本。',
      en: 'The foundational stage of this workflow involves the efficient conversion of existing educational content into an interactive digital format. The success of the entire automated assessment process is contingent upon the quality and accuracy of this initial step, which bridges the gap between legacy materials and modern digital platforms. This approach acknowledges the vast libraries of content educators already possess and provides a direct pathway to digitization without the prohibitive time cost of recreating every assessment from scratch.',
    },
    sections: [
      {
        id: 's1.1',
        title: {
          zh: '1.1: 准备源文档以实现最佳转换',
          en: 'Section 1.1: Preparing Source Documents for Optimal Conversion',
        },
        content: [
          { type: 'paragraph', content: { zh: 'Microsoft Forms 导入引擎的效率与源文档的清晰度和结构直接相关。该算法依赖于逻辑、可预测的格式来准确解析问题和答案。投入时间准备源文档会产生重大影响，因为精心的准备与导入后修正和验证所需的时间成反比。', en: 'The efficacy of the Microsoft Forms import engine is directly proportional to the clarity and structure of the source document. The algorithm relies on logical, predictable formatting to accurately parse questions and answers. Investing time in preparing the source document has a significant impact, as meticulous preparation has an inverse relationship with the time required for post-import correction and validation.' } },
          { type: 'paragraph', content: { zh: '为确保最高保真度的转换，源文档应遵循以下格式指南：', en: 'To ensure the highest fidelity conversion, source documents should adhere to the following formatting guidelines:' } },
          { type: 'list', items: [ { zh: '文档格式：导入过程兼容 Microsoft Word (.docx) 和 PDF (.pdf) 文件。', en: 'Document Format: The import process is compatible with Microsoft Word (`.docx`) and PDF (`.pdf`) files.' }, { zh: '问题与答案结构：所有内容必须垂直组织。每个问题应紧随其潜在答案，每个答案选项另起一行，直接位于前一个选项下方。', en: 'Question and Answer Structure: All content must be organized vertically. Each question should be followed immediately by its potential answers, with each answer option on a new line directly below the previous one.' }, { zh: '元素分隔：必须使用清晰的换行（即空一行）来分隔一个问题-答案块与下一个。这对导入算法来说是一个关键的分隔符，标志着一个问题的结束和下一个问题的开始。', en: 'Separation of Elements: A clear line break (i.e., skipping a line) must be used to separate one question-and-answer block from the next. This acts as a critical delimiter for the import algorithm, signaling the end of one question and the beginning of another.' }, { zh: '支持的问题类型：“快速导入”功能针对多项选择题和开放文本问题类型进行了优化。更复杂的格式，如排序、评级量表（如李克特量表）或日期问题，无法可靠转换，应在初次导入后在 Forms 界面中手动添加。', en: 'Supported Question Types: The "Quick Import" feature is optimized for multiple-choice and open-text question types. More complex formats, such as ranking, rating scales (e.g., Likert), or date questions, are not reliably converted and should be added manually within the Forms interface after the initial import.' }, { zh: '排除复杂元素：为防止转换错误，最好从源文档中移除或简化复杂元素，如嵌入的表格、多列布局或复杂的插图。这些元素可以使用 Microsoft Forms 内的原生工具（如其专用的图片上传或数学方程式功能）以更好的控制和功能重新引入。', en: 'Exclusion of Complex Elements: To prevent conversion errors, it is best practice to remove or simplify complex elements like embedded tables, multi-column layouts, or intricate illustrations from the source document. These elements can be re-introduced with greater control and functionality using the native tools within Microsoft Forms, such as its dedicated image upload or math equation features.' } ] },
        ],
      },
      {
        id: 's1.2',
        title: {
          zh: '1.2: 快速导入流程：分步演练',
          en: 'Section 1.2: The Quick Import Process: A Step-by-Step Walkthrough',
        },
        content: [
          { type: 'paragraph', content: { zh: '有了格式正确的源文档，导入过程就变得很简单。从正确的门户网站启动此过程至关重要，因为“快速导入”功能仅在专用的 Microsoft Forms 网站上可用。', en: 'With a properly formatted source document, the import process is straightforward. It is crucial to initiate this process from the correct web portal, as the "Quick Import" functionality is exclusively available on the dedicated Microsoft Forms site.' } },
          { type: 'paragraph', content: { zh: '分步导入程序如下：', en: 'The step-by-step import procedure is as follows:' } },
          { type: 'list', items: [ { zh: '登录 Microsoft 365 帐户并直接导航到 `https://forms.office.com`。尝试从通用的 `office.com` 门户访问此功能将无法正常工作，这是一个常见的用户错误点。', en: 'Log in to a Microsoft 365 account and navigate directly to `https://forms.office.com`. Attempting to access this feature from the general `office.com` portal will not work, a common point of user error.' }, { zh: '在 Forms 主页上，找到并选择“快速导入”按钮（也可能标记为“导入”）。', en: 'On the Forms homepage, locate and select the **Quick Import** button (this may also be labeled simply as **Import**).' }, { zh: '选择“从此设备上传”选项，这将打开本地系统的文件浏览器。', en: 'Choose the **Upload from this device** option, which will open the local system\'s file explorer.' }, { zh: '选择准备好的 Word 或 PDF 文档进行转换。请注意，源文档的文件大小限制为 10MB。', en: 'Select the prepared Word or PDF document for conversion. Note that there is a file size limitation of 10MB for the source document.' }, { zh: '将出现一个对话框，提示一个关键选择：将文档转换为“表单”或“测验”。要启用自动评分、分数分配和正确答案指定等此工作流程的核心功能，必须选择“测验”。', en: 'A dialog box will appear, prompting a critical choice: convert the document into a **Form** or a **Quiz**. To enable the auto-grading, point allocation, and correct answer designation features central to this workflow, it is imperative to select **Quiz**.' }, { zh: '转换过程将开始。所需时间可能因文档的复杂性和格式而异。虽然两种格式都效果很好，但由于与 Microsoft 生态系统的原生集成，Word 文档的转换速度可能比 PDF 稍快。', en: 'The conversion process will commence. The time required can vary based on document complexity and format. While both formats work well, Word documents may convert slightly faster than PDFs due to their native integration with the Microsoft ecosystem.' } ] },
        ],
      },
      {
        id: 's1.3',
        title: {
          zh: '1.3: 导入后优化和验证',
          en: 'Section 1.3: Post-Import Refinement and Validation',
        },
        content: [
          { type: 'paragraph', content: { zh: '导入过程提供了一个很好的起点，但它不是最终产品。系统性审查是确保数字测验准确并准备好进行配置的关键质量保证步骤。', en: 'The import process provides an excellent starting point, but it is not the final product. A systematic review is a critical quality assurance step to ensure the digital quiz is accurate and ready for configuration.' } },
          { type: 'paragraph', content: { zh: '成功转换后，Microsoft Forms 将显示一条通知。用户应选择“开始审查”选项。这将打开新创建的测验，并通常显示一个侧面板，标记出导入算法在转换过程中检测到的潜在问题。还应使用以下清单进行彻底的手动检查：', en: 'Upon successful conversion, Microsoft Forms will present a notification. The user should select the **Start review** option. This opens the newly created quiz and often displays a side panel that flags potential issues the import algorithm detected during conversion. A thorough manual check should also be conducted using the following checklist:' } },
          { type: 'list', items: [ { zh: '标题和描述：验证测验标题和任何介绍性文本是否已正确解析。在某些情况下，这些元素可能会合并到一个字段中，需要手动分离。', en: 'Title and Description: Verify that the quiz title and any introductory text have been parsed correctly. In some cases, these elements may be merged into a single field and will require manual separation.' }, { zh: '问题完整性：仔细阅读每个问题，以识别转换过程中可能出现的任何格式错误、字符误解或文本混乱。', en: 'Question Integrity: Carefully read through each question to identify any formatting errors, misinterpreted characters, or garbled text that may have occurred during the conversion.' }, { zh: '答案选项准确性：对于所有多项选择题，确认每个答案选项都存在、措辞正确，并与其相应的问题正确关联。', en: 'Answer Option Accuracy: For all multiple-choice questions, confirm that every answer option is present, correctly worded, and properly associated with its corresponding question.' }, { zh: '问题类型分配：导入器根据对源文档的分析分配问题类型（例如，多项选择题为“选择”，开放式问题为“文本”）。验证这些分配是否正确，并手动更改任何被误解的问题的类型。', en: 'Question Type Assignment: The importer assigns a question type (e.g., \'Choice\' for multiple-choice, \'Text\' for open-ended) based on its analysis of the source document. Verify that these assignments are correct and manually change the type for any question that was misinterpreted.' }, { zh: '最终确定：一旦审查面板中所有标记的问题都已解决并且手动验证完成，测验就准备好进入下一阶段的配置。', en: 'Finalization: Once all flagged issues in the review panel have been addressed and the manual verification is complete, the quiz is ready for the next stage of configuration.' } ] },
        ],
      },
    ],
  },
  {
    id: 'part2',
    title: {
      zh: '第二部分：配置测验以进行自动化评估',
      en: 'Part II: Configuring Your Quiz for Automated Assessment',
    },
    introduction: {
      zh: '此阶段从内容创建过渡到功能配置。在这里，导入的问题被转换为能够自动评分、定时交付和控制学生反馈的智能评估工具。“表单”和“测验”之间的区别是整个过程的基础，因为“测验”的指定解锁了必要的评估功能。',
      en: 'This phase transitions from content creation to functional configuration. Here, the imported questions are transformed into an intelligent assessment tool capable of automatic grading, timed delivery, and controlled student feedback. The distinction between a "Form" and a "Quiz" is foundational to this entire process, as the "Quiz" designation unlocks the necessary assessment features.',
    },
    sections: [
      {
        id: 's2.0',
        title: { zh: '', en: '' },
        content: [
          { type: 'table', caption: { zh: '表 1：Microsoft "表单" vs. "测验" - 对比分析', en: 'Table 1: Microsoft "Form" vs. "Quiz" - A Comparative Analysis' }, headers: [ { zh: '功能', en: 'Feature' }, { zh: 'Microsoft 表单 (调查)', en: 'Microsoft Form (Survey)' }, { zh: 'Microsoft 测验 (评估)', en: 'Microsoft Quiz (Assessment)' } ], rows: [ [ { zh: '主要目的', en: 'Primary Purpose' }, { zh: '数据/意见收集', en: 'Data/Opinion Collection' }, { zh: '知识评估', en: 'Knowledge Evaluation' } ], [ { zh: '分值', en: 'Point Values' }, { zh: '不可用', en: 'Not Available' }, { zh: '每题可用', en: 'Available per Question' } ], [ { zh: '正确答案指定', en: 'Correct Answer Designation' }, { zh: '不可用', en: 'Not Available' }, { zh: '可用于自动评分', en: 'Available for Auto-Grading' } ], [ { zh: 'Teams 作业集成', en: 'Teams Assignment Integration' }, { zh: '有限（仅链接）', en: 'Limited (Link only)' }, { zh: '原生集成 (创建 > 测验)', en: 'Native Integration (Create > Quiz)' } ], [ { zh: '学生反馈', en: 'Student Feedback' }, { zh: '不适用', en: 'N/A' }, { zh: '即时/延迟分数和答案审查', en: 'Immediate/Delayed Score & Answer Review' } ] ] },
          { type: 'paragraph', content: { zh: '如表所示，在导入或创建过程中选择“测验”对于构建自动化评估是不可协商的。此选择从根本上改变了可用的工具集，启用了下面详述的功能。', en: 'As the table illustrates, selecting "Quiz" during the import or creation process is non-negotiable for building an automated assessment. This choice fundamentally alters the available toolset, enabling the features detailed below.' } },
        ],
      },
      {
        id: 's2.1',
        title: {
          zh: '2.1: 掌握自动评分要点',
          en: 'Section 2.1: Mastering Auto-Grading Essentials',
        },
        content: [
          { type: 'paragraph', content: { zh: '这是自动化的核心，将智能嵌入到测验中，以实现即时、准确的评分。', en: 'This is the core of the automation, where the intelligence is embedded into the quiz to enable instant, accurate scoring.' } },
          { type: 'list', items: [ { zh: '指定正确答案：要为多项选择题设置正确答案，请单击问题进入其编辑模式。将鼠标悬停在所需的答案选项上，然后单击右侧出现的勾选/复选标记图标。绿色复选标记将确认此选项现在已注册为自动评分的正确响应。', en: 'Designating Correct Answers: To set the correct answer for a multiple-choice question, click on the question to enter its edit mode. Hover over the desired answer option and click the **tick/check mark icon** that appears to the right. A green check mark will confirm that this option is now registered as the correct response for auto-grading.' }, { zh: '处理多个正确答案：如果一个问题有多个有效答案，请激活问题编辑面板底部的“多个答案”切换开关。这将把学生的选项格式从单选按钮更改为复选框，并允许创建者为多个正确选项选择复选标记。', en: 'Handling Multiple Correct Answers: If a question has more than one valid answer, activate the **Multiple answers** toggle switch at the bottom of the question\'s edit panel. This will change the selection format from radio buttons to checkboxes for students and allow the creator to select the check mark for multiple correct options.' }, { zh: '分配分值：在每个问题的编辑面板中，找到“分数”输入框。输入一个数值，表示该问题正确答案的分数。此值对于自动计算学生的总分至关重要。', en: 'Assigning Point Values: In each question\'s edit panel, locate the **Points** input box. Enter a numerical value that represents the score for a correct answer to that question. This value is essential for the automatic calculation of the student\'s total score.' }, { zh: '要求回答：为防止学生意外跳过问题，请激活“必需”切换开关。此设置确保学生在为每个必需问题提供答案之前无法提交测验。', en: 'Requiring a Response: To prevent students from accidentally skipping a question, activate the **Required** toggle switch. This setting ensures that a student cannot submit the quiz until an answer has been provided for every required question.' } ] },
        ],
      },
      {
        id: 's2.2',
        title: {
          zh: '2.2: 高级测验控制：计时器和演示',
          en: 'Section 2.2: Advanced Quiz Controls: Timers and Presentation',
        },
        content: [
          { type: 'paragraph', content: { zh: '这些功能增强了评估的完整性并改善了学生体验。它们不仅仅是技术开关，而是教学策略的杠杆，允许教育工作者将评估从开卷练习转变为在受控条件下衡量回忆和流畅性的方式。', en: 'These features enhance the integrity of the assessment and improve the student experience. They are not merely technical toggles but levers for pedagogical strategy, allowing an educator to shift an assessment from an open-book exercise to a measure of recall and fluency under controlled conditions.' } },
          { type: 'list', items: [ { zh: '设置时间限制：要对测验施加时间限制，请单击 Forms 界面右上角的省略号 (...) 并选择“设置”。在出现的“设置”窗格中，选中“设置持续时间”复选框，并输入学生完成评估的总分钟数。一旦学生开始测验，计时器将显着显示。', en: 'Setting a Time Limit: To impose a time constraint on the quiz, click the **ellipsis (...)** in the top-right corner of the Forms interface and select **Settings**. In the Settings pane that appears, check the box for **Set time duration** and enter the total number of minutes students will have to complete the assessment. Once a student starts the quiz, a timer will be prominently displayed.' }, { zh: '自定义视觉主题：为增强学生参与度，可以自定义测验的视觉外观。单击顶部菜单栏中的“主题”或“样式”按钮。这允许选择预制配色方案和背景图像，或上传自定义图像以与主题或班级品牌保持一致。', en: 'Customizing the Visual Theme: To enhance student engagement, the visual appearance of the quiz can be customized. Click the **Theme** or **Style** button in the top menu bar. This allows for the selection of pre-made color schemes and background images, or the uploading of a custom image to align with the topic or class branding.' } ] },
          { type: 'warning', content: { zh: '关于定时提交的关键警告：定时测验功能存在重大风险。虽然某些界面文本可能暗示当计时器到期时响应会自动提交，但实际用户报告和支持声明表明此功能可能会失败。如果学生在计时器用完之前没有手动单击“提交”按钮，他们的作业可能会丢失且不被记录。因此，教育工作者必须向学生提供明确的指示，指导他们在计时器归零之前手动提交测验，以确保他们的回答被捕获。', en: 'Critical Warning on Timed Submissions: There is a significant risk associated with the timed quiz feature. While some interface text may imply that responses are automatically submitted when the timer expires, real-world user reports and support statements indicate that this functionality can fail. If a student does not manually click the "Submit" button before the timer runs out, their work may be lost and not recorded. Therefore, it is imperative that educators provide explicit instructions to their students, directing them to manually submit their quiz before the timer reaches zero to ensure their responses are captured.' } }
        ],
      },
      {
        id: 's2.3',
        title: {
          zh: '2.3: 管理学生体验：结果可见性和反馈',
          en: 'Section 2.3: Managing the Student Experience: Result Visibility and Feedback',
        },
        content: [
          { type: 'paragraph', content: { zh: '本节中的设置控制提交后信息流回学生的方式。这是一个关键的教学决策，决定了评估是用于形成性（即时反馈以供学习）还是总结性（延迟的、正式的评估）目的。', en: 'The settings in this section control the flow of information back to the student after submission. This is a key pedagogical decision, determining whether the assessment serves a formative (immediate feedback for learning) or summative (delayed, formal evaluation) purpose.' } },
          { type: 'paragraph', content: { zh: '控制分数和答案可见性：导航到“设置”窗格，方法是单击省略号 (...) 并选择“设置”。找到“自动显示结果”的切换开关。', en: 'Controlling Score and Answer Visibility: Navigate to the **Settings** pane by clicking the ellipsis (...) and selecting **Settings**. Locate the toggle for **Show results automatically**.' } },
          { type: 'list', items: [ { zh: '启用（默认）：启用此设置后，学生在提交测验后将立即看到他们的最终分数和答案回顾——指示哪些是正确的，哪些是错误的。这对于形成性评估、家庭作业检查和复习练习是理想的，因为即时反馈有利于学习。', en: 'Enabled (Default): With this setting on, students will immediately see their final score and a review of their answers—indicating which were correct and incorrect—upon submitting the quiz. This is ideal for formative assessments, homework checks, and revision exercises where instant feedback is beneficial for learning.' }, { zh: '禁用：关闭此设置后，学生提交后只会看到一条通用的确认消息。他们的分数和结果将被保留，直到教育工作者选择手动审查并“发布”它们。这种方法对于总结性评估（如大考或期末考试）至关重要，因为分数必须经过审查以确保公平性或同时向全班公布。', en: 'Disabled: When this setting is turned off, students will only see a generic confirmation message after submission. Their scores and results are withheld until the educator chooses to manually review and "post" them. This approach is essential for summative assessments like major tests or exams, where scores must be reviewed for fairness or released to the entire class simultaneously.' } ] },
        ],
      },
    ],
  },
  {
    id: 'part3',
    title: {
      zh: '第三部分：通过 Microsoft Teams 分发和管理测验',
      en: 'Part III: Distributing and Managing Quizzes via Microsoft Teams',
    },
    introduction: {
      zh: 'Microsoft Teams 是整个评估过程的中央指挥中心。虽然 Microsoft Forms 是测验创建和配置的引擎，但 Teams 处理交付、调度、差异化和成绩管理等关键后勤组件。这种集成是整个工作流程效率和功能强大的关键。',
      en: 'Microsoft Teams serves as the central command center for the entire assessment process. While Microsoft Forms is the engine for quiz creation and configuration, Teams handles the critical logistical components of delivery, scheduling, differentiation, and grade management. This integration is the key to the workflow\'s overall efficiency and power.',
    },
    sections: [
      {
        id: 's3.1',
        title: {
          zh: '3.1: 创建和附加测验作业',
          en: 'Section 3.1: Creating and Attaching a Quiz Assignment',
        },
        content: [
          { type: 'paragraph', content: { zh: '分配已配置测验的过程完全在熟悉的 Microsoft Teams 环境中进行。', en: 'The process of assigning the configured quiz takes place entirely within the familiar Microsoft Teams environment.' } },
          { type: 'list', items: [ { zh: '导航到作业选项卡：在所需的班级团队中，导航到“作业”选项卡，该选项卡通常位于“常规”频道中，或从左侧导航栏打开专用的“作业”应用程序。', en: 'Navigating to the Assignments Tab: In the desired Class Team, navigate to the **Assignments** tab, typically located in the General channel, or open the dedicated Assignments app from the left-hand navigation bar.' }, { zh: '创建新的测验作业：单击“创建”按钮，然后从下拉菜单中选择“测验”。一个新的窗口将打开，显示与用户 Microsoft Forms 帐户关联的所有可用测验列表。选择在第二部分中配置的测验，然后单击“下一步”。', en: 'Creating a New Quiz Assignment: Click the **Create** button and select **Quiz** from the dropdown menu. A new window will open, displaying a list of all available quizzes associated with the user\'s Microsoft Forms account. Select the quiz that was configured in Part II and click **Next**.' } ] },
          { type: 'paragraph', content: { zh: '填充作业详细信息：系统将自动附加测验并填充作业创建屏幕。测验标题和总分将直接从表单中导入。然后，教育工作者应在提供的文本框中为学生添加清晰的“说明”，以确保他们了解评估的期望。', en: 'Populating Assignment Details: The system will automatically attach the quiz and populate the assignment creation screen. The quiz title and the total possible points will be imported directly from the Form. The educator should then add clear **Instructions** for students in the provided text box to ensure they understand the expectations for the assessment.' } },
        ],
      },
      {
        id: 's3.2',
        title: {
          zh: '3.2: 微调作业参数',
          en: 'Section 3.2: Fine-Tuning Assignment Parameters',
        },
        content: [
          { type: 'paragraph', content: { zh: 'Teams 作业中的设置提供了对评估生命周期的精细控制。特别是调度功能，可以从根本上将教育工作者的工作流程从被动变为主动。', en: 'The settings within a Teams assignment provide granular control over the assessment\'s lifecycle. The scheduling features, in particular, can fundamentally change an educator\'s workflow from reactive to proactive.' } },
          { type: 'table', caption: { zh: '表 2：理解 Microsoft Teams 中的作业时间线设置', en: 'Table 2: Understanding Assignment Timeline Settings in Microsoft Teams' }, headers: [ { zh: '设置', en: 'Setting' }, { zh: '功能', en: 'Function' }, { zh: '对学生的影响', en: 'Impact on Student' }, { zh: '最佳实践用例', en: 'Best Practice Use Case' } ], rows: [ [ { zh: '发布日期', en: 'Post Date' }, { zh: '定义作业对学生可见和可访问的确切日期和时间。', en: 'Defines the exact date and time the assignment becomes visible and accessible to students.' }, { zh: '在此时间之前，作业不会出现在他们的列表中。', en: 'The assignment does not appear in their list until this time.' }, { zh: '提前准备作业并安排它们在课程或一周开始时自动发布。', en: 'Preparing assignments in advance and scheduling them to release automatically at the start of a lesson or week.' } ], [ { zh: '截止日期', en: 'Due Date' }, { zh: '提交的正式截止日期。', en: 'The official deadline for submission.' }, { zh: '在此时间之后提交的作业在成绩簿中标记为“迟交”。', en: 'Submissions after this time are marked as \'Late\' in the gradebook.' }, { zh: '为学生设定完成工作的明确目标。', en: 'Setting a clear target for students to complete the work.' } ], [ { zh: '关闭日期', en: 'Close Date' }, { zh: '硬性截止日期，之后不接受任何提交（包括迟交）。', en: 'The hard cutoff after which no submissions (including late ones) are accepted.' }, { zh: '在此时间之后，作业将无法访问且无法上交。', en: 'The assignment becomes inaccessible and cannot be turned in after this time.' }, { zh: '强制执行严格的最终截止日期，并在一定的宽限期后阻止提交。', en: 'Enforcing a strict final deadline and preventing submissions after a certain grace period has passed.' } ] ] },
          { type: 'paragraph', content: { zh: '配置时间线：可以直接在主作业屏幕上设置“截止日期”和时间。要访问更高级的选项，请单击截止日期字段下方的“编辑”按钮。这将打开“编辑作业时间线”菜单，可以在其中配置“发布日期”（标记为“安排在将来分配”）和“关闭日期”的具体日期和时间。', en: 'Configuring the Timeline: The **Due date** and time can be set directly on the main assignment screen. To access the more advanced options, click the **Edit** button located under the due date field. This opens the "Edit assignment timeline" menu, where the **Post Date** (labeled as "Schedule to assign in the future") and the **Close Date** can be configured with specific dates and times.' } },
        ],
      },
    ],
  },
  {
    id: 'part4',
    title: {
      zh: '第四部分：分析结果和提供反馈',
      en: 'Part IV: Analyzing Results and Providing Feedback',
    },
    introduction: {
      zh: '工作流程的最后一部分侧重于利用收集到的数据进行评分、反馈和长期分析。该系统提供了两种不同但互补的评估数据视图：Microsoft Forms 中的深度诊断视图和 Microsoft Teams 中的高级管理视图。',
      en: 'The final part of the workflow focuses on leveraging the collected data for grading, feedback, and long-term analysis. The system provides two distinct but complementary views of the assessment data: a deep, diagnostic view within Microsoft Forms, and a high-level, administrative view within Microsoft Teams.',
    },
    sections: [
      {
        id: 's4.1',
        title: {
          zh: '4.1: Forms 中的“回复”仪表板：即时分析洞察',
          en: 'Section 4.1: The \'Responses\' Dashboard in Forms: Immediate Analytical Insights',
        },
        content: [
          { type: 'paragraph', content: { zh: '对于详细的教学分析，Microsoft Forms 的“回复”选项卡提供了丰富的实时数据可视化。', en: 'For detailed pedagogical analysis, the Microsoft Forms "Responses" tab offers rich, real-time data visualizations.' } },
          { type: 'paragraph', content: { zh: '要查看结果，请在 Microsoft Forms 中打开特定的测验，然后单击屏幕顶部的“回复”选项卡。仪表板提供了班级表现的即时概览，包括回复总数、平均完成时间和测验状态。', en: 'To view the results, open the specific quiz within Microsoft Forms and click on the **Responses** tab located at the top of the screen. The dashboard provides an immediate overview of class performance, including the total number of responses, the average time students took to complete the quiz, and the quiz\'s current status.' } },
        ],
      },
      {
        id: 's4.2',
        title: {
          zh: '4.2: 精细审查和手动调整',
          en: 'Section 4.2: Granular Review and Manual Adjustments',
        },
        content: [
          { type: 'paragraph', content: { zh: '要从班级级摘要转向个别学生表现，请使用 Forms 中的审查工具。这是自动化工作流程与教育工作者专业判断和定性反馈相结合的地方。', en: 'To move from class-level summaries to individual student performance, the review tools in Forms are used. This is where the automated workflow is supplemented with the educator\'s professional judgment and qualitative feedback.' } },
          { type: 'list', items: [ { zh: '审查个人答案：在“回复”选项卡上，单击“审查答案”按钮。这将打开一个界面，允许教育工作者逐个滚动浏览每个学生的提交。', en: 'Reviewing Individual Answers: On the Responses tab, click the **Review answers** button. This opens an interface that allows the educator to scroll through each student\'s submission individually.' }, { zh: '提供个性化反馈：对于任何问题，反馈图标允许教育工作者输入特定评论，提供超越简单数字分数的定性反馈。', en: 'Providing Personalized Feedback: For any question, a feedback icon allows the educator to type a specific comment, providing qualitative feedback that goes beyond a simple numerical score.' }, { zh: '覆盖分数和评分开放式问题：对于需要手动评估的开放式文本问题，教育工作者可以直接输入分数。系统还允许手动覆盖任何自动评分的分数。', en: 'Overriding Scores and Grading Open-Ended Questions: For open-text questions that require manual evaluation, the educator can enter the appropriate point value directly. The system also allows for the manual override of any auto-graded score.' }, { zh: '发布分数：所有审查、手动评分和反馈完成后，教育工作者必须单击“发布分数”。此操作将最终成绩和所有个性化反馈发布给学生。', en: 'Posting Scores: After all reviews, manual grading, and feedback are complete, the educator must click **Post scores**. This action releases the final grades and all personalized feedback to the students.' } ] },
        ],
      },
      {
        id: 's4.3',
        title: {
          zh: '4.3: Teams“成绩”选项卡中的集中式成绩管理',
          en: 'Section 4.3: Centralized Grade Management in the Teams \'Grades\' Tab',
        },
        content: [
          { type: 'paragraph', content: { zh: '出于管理目的，所有分数都会自动整合到 Microsoft Teams 成绩簿中，为学生在所有作业中的表现提供单一的真实来源。', en: 'For administrative purposes, all scores are automatically consolidated within the Microsoft Teams gradebook, providing a single source of truth for student performance across all assignments.' } },
          { type: 'list', items: [ { zh: '自动成绩同步：当学生完成通过 Teams 分配的测验时，他们的分数会自动填充到 Teams 成绩簿中。在 Forms 中输入的任何手动调整或分数在发布后也会同步。', en: 'Automatic Grade Syncing: When a student completes a quiz assigned through Teams, their score is automatically populated in the Teams gradebook. Any manual adjustments or scores entered in Forms will also sync back after they are posted.' }, { zh: '在 Teams 中查看成绩：要访问班级成绩簿，请导航到班级团队中的“成绩”选项卡。这将显示一个全面的网格，其中包含学生姓名和所有作业，提供对班级进度的集中概览。', en: 'Viewing Grades in Teams: To access the class gradebook, navigate to the **Grades** tab within the Class Team. This displays a comprehensive grid with student names and all assignments, offering a centralized overview of class progress.' } ] },
        ],
      },
    ],
  },
  {
    id: 'conclusion-part',
    title: {
      zh: '结论和最佳实践清单',
      en: 'Conclusion and Best Practices Checklist',
    },
    introduction: {
      zh: 'Microsoft Forms 和 Microsoft Teams 的集成为创建、分发和分析数字评估提供了一个强大的端到端解决方案。通过转换现有文档、配置智能测验以及利用 Teams 强大的作业功能，教育工作者可以自动化其评估工作量的很大一部分。这种自动化创造了将焦点从死记硬背的行政任务转移到有意义的数据分析和个性化学生参与的机会。',
      en: 'The integration of Microsoft Forms and Microsoft Teams offers a powerful, end-to-end solution for creating, distributing, and analyzing digital assessments. By converting existing documents, configuring intelligent quizzes, and leveraging the robust assignment features of Teams, educators can automate a significant portion of their assessment workload. This automation creates the opportunity to shift focus from rote administrative tasks to meaningful data analysis and personalized student engagement.',
    },
    sections: [
      {
        id: 's-conclusion',
        title: {
          zh: '为确保此工作流程的顺利有效实施，应遵守以下最佳实践：',
          en: 'To ensure a smooth and effective implementation of this workflow, the following best practices should be observed:',
        },
        content: [
          { type: 'list', items: [ { zh: '优先准备文档：使用简单的垂直布局和问题之间清晰的换行来构建源 Word 或 PDF 文件，以确保最高质量的导入。', en: 'Prioritize Document Preparation: Structure source Word or PDF files with a simple, vertical layout and clear line breaks between questions to ensure the highest quality import.' }, { zh: '始终选择“测验”：在导入过程或从头开始创建新评估时，始终选择“测验”选项以解锁必要的自动评分和分值功能。', en: 'Always Select \'Quiz\': During the import process or when creating a new assessment from scratch, always choose the **Quiz** option to unlock essential auto-grading and point-value features.' }, { zh: '导入后验证：在进一步配置之前，彻底审查每个导入的测验是否存在格式错误，尤其是在标题、问题和答案选项中。', en: 'Validate After Import: Thoroughly review every imported quiz for formatting errors, especially in titles, questions, and answer options, before configuring it further.' }, { zh: '警告学生关于定时测验：明确指示学生必须在计时器到期前手动单击“提交”按钮，因为自动提交功能并非始终可靠，可能导致数据丢失。', en: 'Warn Students About Timed Quizzes: Explicitly instruct students that they must manually click the "Submit" button before a timer expires, as the automatic submission feature is not consistently reliable and can lead to data loss.' }, { zh: '利用作业调度：使用 Teams 中的“安排在将来分配”功能提前准备和安排作业，将工作流程从每日的被动任务转变为定期的主动任务。', en: 'Leverage Assignment Scheduling: Use the "Schedule to assign in the future" feature in Teams to prepare and schedule assignments in advance, transforming workflow from a daily reactive task to a periodic proactive one.' }, { zh: '区分截止日期和关闭日期：理解并使用 Teams 作业中的“关闭日期”设置来强制执行硬性截止日期并有意控制延迟提交。', en: 'Distinguish Between Due Date and Close Date: Understand and use the "Close Date" setting in Teams assignments to enforce hard deadlines and control late submissions intentionally.' }, { zh: '使用正确的工具进行分析：利用 Microsoft Forms 中的“回复”选项卡对问题级数据和全班趋势进行深入的教学分析。使用 Microsoft Teams 中的“成绩”选项卡进行高级行政成绩管理和报告。', en: 'Use the Right Tool for Analysis: Utilize the **Responses** tab in Microsoft Forms for deep pedagogical analysis of question-level data and class-wide trends. Use the **Grades** tab in Microsoft Teams for high-level administrative grade management and reporting.' } ] },
        ],
      },
    ],
  },
];


//-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
// REACT COMPONENT
//-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=

const AutomatedAssessmentGuide = (): React.ReactElement => {
  const [currentLang, setCurrentLang] = useState<'zh' | 'en'>('zh');

  const getText = (text: LanguageText): string => text[currentLang];

  const toggleLanguage = (): void => {
    setCurrentLang(prevLang => (prevLang === 'zh' ? 'en' : 'zh'));
  };
  
  const renderContent = (contentItem: SectionContent, index: number): React.ReactElement => {
    switch (contentItem.type) {
      case 'paragraph':
        return <p key={index} className="mb-4 text-slate-600 dark:text-slate-300 leading-relaxed">{getText(contentItem.content)}</p>;
      case 'list':
        return (
          <ul key={index} className="mb-4 list-disc list-inside space-y-2 pl-4 text-slate-600 dark:text-slate-300">
            {contentItem.items.map((item, i) => <li key={i} dangerouslySetInnerHTML={{ __html: getText(item).replace(/\*\*(.*?)\*\*/g, '<strong>$1</strong>') }}></li>)}
          </ul>
        );
      case 'table':
        return (
          <div key={index} className="my-8 overflow-x-auto">
            <figure>
              <table className="w-full min-w-[600px] border-collapse text-sm text-left">
                <caption className="text-lg font-semibold p-2 bg-slate-100 dark:bg-slate-700 text-slate-800 dark:text-slate-100 rounded-t-lg">{getText(contentItem.caption)}</caption>
                <thead className="bg-slate-200 dark:bg-slate-800">
                  <tr>
                    {contentItem.headers.map((header, i) => (
                      <th key={i} scope="col" className="p-3 font-semibold text-slate-700 dark:text-slate-200">{getText(header)}</th>
                    ))}
                  </tr>
                </thead>
                <tbody className="bg-white dark:bg-slate-900">
                  {contentItem.rows.map((row, i) => (
                    <tr key={i} className="border-b border-slate-200 dark:border-slate-700">
                      {row.map((cell, j) => (
                        <td key={j} className="p-3 text-slate-600 dark:text-slate-300">{getText(cell)}</td>
                      ))}
                    </tr>
                  ))}
                </tbody>
              </table>
            </figure>
          </div>
        );
        case 'warning':
            return (
                <div key={index} className="my-6 p-4 border-l-4 border-amber-500 bg-amber-100 dark:bg-amber-900/30 rounded-r-lg">
                    <div className="flex">
                        <div className="flex-shrink-0">
                             <svg className="h-5 w-5 text-amber-500" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
                                <path fillRule="evenodd" d="M8.257 3.099c.625-1.09 2.13-1.09 2.755 0l6.93 12.128c.626 1.09-.123 2.473-1.377 2.473H2.704c-1.254 0-2.003-1.383-1.377-2.473L8.257 3.099zM9 10a1 1 0 112 0v3a1 1 0 11-2 0v-3zm2 5a1 1 0 11-2 0 1 1 0 012 0z" clipRule="evenodd" />
                            </svg>
                        </div>
                        <div className="ml-3">
                            <p className="text-sm text-amber-700 dark:text-amber-300">{getText(contentItem.content)}</p>
                        </div>
                    </div>
                </div>
            );
        case 'image':
            return (
                <figure key={index} className="my-6 text-center">
                    <img src={contentItem.src} alt={getText(contentItem.alt)} className="max-w-full md:max-w-2xl mx-auto rounded-lg shadow-md border border-slate-200 dark:border-slate-700" />
                    {contentItem.caption && (
                        <figcaption className="mt-2 text-sm text-slate-500 dark:text-slate-400 italic">
                            {getText(contentItem.caption)}
                        </figcaption>
                    )}
                </figure>
            );
      default:
        return <></>;
    }
  };

  const introPart = useMemo(() => guideData.find(p => p.id === 'intro-part'), []);
  const mainParts = useMemo(() => guideData.filter(p => p.id !== 'intro-part' && p.id !== 'conclusion-part'), []);
  const conclusionPart = useMemo(() => guideData.find(p => p.id === 'conclusion-part'), []);

  return (
    <div className="bg-slate-50 dark:bg-slate-900 font-sans text-slate-900 dark:text-slate-100 min-h-screen">
      
      <div className="fixed top-4 right-4 z-50">
        <button 
          onClick={toggleLanguage}
          aria-label="Toggle Language"
          className="bg-white dark:bg-slate-800 shadow-lg rounded-full p-3 text-sm font-medium hover:bg-slate-100 dark:hover:bg-slate-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500 dark:focus:ring-offset-slate-900 transition-transform duration-200 hover:scale-105"
        >
          <span className={currentLang === 'zh' ? 'text-indigo-500 font-bold' : 'text-slate-500'}>中</span>
          <span className="mx-1 text-slate-300 dark:text-slate-600">/</span>
          <span className={currentLang === 'en' ? 'text-indigo-500 font-bold' : 'text-slate-500'}>EN</span>
        </button>
      </div>

      <main className="container mx-auto px-4 py-8 md:py-16">
        
        {introPart && (
            <header className="text-center mb-16">
                <div className="inline-block bg-gradient-to-r from-indigo-500 to-purple-600 p-1 rounded-xl shadow-lg">
                    <div className="bg-white dark:bg-slate-800 rounded-lg px-4 py-2">
                        <h1 className="text-3xl md:text-5xl font-extrabold bg-clip-text text-transparent bg-gradient-to-r from-indigo-500 to-purple-600">
                        {getText(introPart.title)}
                        </h1>
                    </div>
                </div>
                {introPart.introduction && (
                    <p className="mt-6 max-w-3xl mx-auto text-lg text-slate-600 dark:text-slate-300">
                    {getText(introPart.introduction)}
                    </p>
                )}
            </header>
        )}

        <div className="space-y-12">
          {mainParts.map(part => (
            <section key={part.id} aria-labelledby={part.id} className="p-6 md:p-8 bg-white dark:bg-slate-800/50 rounded-2xl shadow-md border border-slate-200 dark:border-slate-700">
              <h2 id={part.id} className="text-2xl md:text-3xl font-bold text-indigo-600 dark:text-indigo-400 mb-4 pb-2 border-b-2 border-indigo-200 dark:border-indigo-800">
                {getText(part.title)}
              </h2>
              {part.introduction && <p className="mb-6 text-slate-600 dark:text-slate-300 italic">{getText(part.introduction)}</p>}
              
              <div className="space-y-8">
                {part.sections.map(section => (
                  <article key={section.id} aria-labelledby={section.id}>
                    {section.title.en && section.title.zh && (
                        <h3 id={section.id} className="text-xl font-semibold text-slate-800 dark:text-slate-100 mb-3">
                        {getText(section.title)}
                        </h3>
                    )}
                    <div>
                      {section.content.map((contentItem, index) => renderContent(contentItem, index))}
                    </div>
                  </article>
                ))}
              </div>
            </section>
          ))}
        </div>
        
        {conclusionPart && (
            <footer className="mt-16 pt-8 border-t-2 border-slate-200 dark:border-slate-700">
                 <section key={conclusionPart.id} aria-labelledby={conclusionPart.id}>
                    <h2 id={conclusionPart.id} className="text-2xl md:text-3xl font-bold text-center text-indigo-600 dark:text-indigo-400 mb-4">
                        {getText(conclusionPart.title)}
                    </h2>
                    {conclusionPart.introduction && <p className="mb-6 max-w-3xl mx-auto text-center text-slate-600 dark:text-slate-300">{getText(conclusionPart.introduction)}</p>}
                    
                    <div className="max-w-3xl mx-auto">
                        {conclusionPart.sections.map(section => (
                        <article key={section.id} aria-labelledby={section.id}>
                            {section.title.en && section.title.zh && (
                                <h3 id={section.id} className="text-lg font-semibold text-slate-800 dark:text-slate-100 mb-3 text-center">
                                {getText(section.title)}
                                </h3>
                            )}
                            <div>
                            {section.content.map((contentItem, index) => renderContent(contentItem, index))}
                            </div>
                        </article>
                        ))}
                    </div>
                </section>
            </footer>
        )}

      </main>
    </div>
  );
};

export default AutomatedAssessmentGuide;
